@startuml
title Warmhouse Context Diagram

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user, "Пользователь", "Владелец умного дома")

System_Boundary(smart_home, "Smart Home") {
    System(device_mgmt, "Device Management", "Учёт датчиков, привязка к локации, управление отоплением")
    System(temp_telemetry, "Temperature Telemetry", "Получение и отображение показаний температуры")
}

System_Ext(temperature_api, "Temperature API", "Внешний API температуры по location")

Rel(user, device_mgmt, "Управляет датчиками")
Rel(user, temp_telemetry, "Просматривает температуру")
Rel(temp_telemetry, device_mgmt, "Использует идентификатор и локацию датчиков")
Rel(temp_telemetry, temperature_api, "Запрашивает показания", "HTTP")

@enduml
